### ISSUE TITLE
Please add Ctrl+Q shortcut for exiting app

### ISSUE THREAD

**Issue by anonymous-user** [son-link/PQMusic#5]
This is a very common keyboard shortcut among GUI applications and it would handy for keyboard focused users.

**Comment by son-link** [comment]
I'm working on it, and I'm already taking advantage of it and adding other keyboard shortcuts.

**Comment by son-link** [comment]
Added this and other shortcuts on the new release:
https://github.com/son-link/PQMusic/releases/tag/v.1.2.1

**Comment by son-link** [comment]
Added this and other shortcuts on the new release:
https://github.com/son-link/PQMusic/releases/tag/v.1.2.1
